version: '3'

services:
  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - 443:443
    volumes:
      - wordpress_data:/var/www/html
    restart: always
    networks:
      - network

  mariadb:
    container_name: mariadb
    build: ./mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    env_file:
      - .env
    networks:
      - network
    restart: always

  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    build: ./wordpress
    restart: always
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - network

  adminer:
    container_name: adminer
    build: ./bonus/adminer
    restart: always
    depends_on:
      - mariadb
    expose:
      - "9000"
    networks:
      - network
      
  website:
    container_name: website
    build: ./bonus/website
    restart: always
    networks:
      - network
      
  nextjs:
    container_name: nextjs
    build: ./bonus/nextjs
    restart: always
    networks:
      - network

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/pdelanno/data/mysql
      o: bind
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/pdelanno/data/wordpress
      o: bind

networks:
  network:
    driver: bridge
